require('plugins')
require('globals')
require('keymaps')
require('settings')
require('theme.catpuccin')

-- Plugins
require('config.nvim-autopairs')
require('config.nvim-barbar')
require('config.nvim-comment')
require('config.nvim-diffview')
require('config.nvim-easyalign')
require('config.nvim-floaterm')
require('config.nvim-fzf-lua')
require('config.nvim-gitblame')
require('config.nvim-gitsigns')
require('config.nvim-hop')
require('config.nvim-lightbulb')
require('config.nvim-matchup')
require('config.nvim-multi-cursor')
require('config.nvim-neoscroll')
require('config.nvim-numb')
require('config.nvim-quickscope')
require('config.nvim-stripwhitespace')
require('config.nvim-tailwindcss')
require('config.nvim-telescope')
require('config.nvim-tree')
require('config.nvim-treesitter')
require('config.nvim-whichkey')
require('config.nvim-windowswap')
require('config.nvim-indent-blankline')
require('config.nvim-trouble')
require('config.nvim-galaxyline')
require('config.nvim-notify')
require('config.nvim-lint')
require('config.nvim-neoclip')
require('config.nvim-colorizer')
require('config.nvim-cmp')
require('config.nvim-cmp-tabnine')

-- LSP
require('lsp')
require('lsp.bash')
require('lsp.php')
require('lsp.lua')
require('lsp.python')
require('lsp.vim')
require('lsp.json')
require('lsp.yaml')
require('lsp.html')
require('lsp.css')
require('lsp.tsserver')
require('lsp.tailwindcss')
require('lsp.omnisharp')
require('lsp.graphql')
require('lsp.volar')

